# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7507820abb53722f3e1c7eeaf8aeb7ce5119e5bbad06b43a974778ce00c69668d90173385f481a6d5874f0731639ad9df8eb47260cad33e20a46f8bb971b3b6

test:
  secret_key_base: f8f82f595f32dc49a82afb7dabd193307f0bbda530fbc364668e4c6b9896c2113bd8cf81e316c4ee83030dd3c2d6384b58c828568731da54dbb54c7e2930a7fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
